version: "3.9"

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "4002:4002"
    env_file: .env
    environment:
      - PORT=4002
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.devreviewapi.rule=Host(`devreview-api.elorchi.com`)"
      - "traefik.http.services.devreviewapi.loadbalancer.server.port=4002"
      - "traefik.http.routers.devreviewapi.entrypoints=websecure"
      - "traefik.http.routers.devreviewapi.tls.certresolver=letsencrypt"
    networks:
      - dokploy-network
      - default
    depends_on:
      - redis

  worker:
    build: .
    restart: unless-stopped
    command: ["node", "dist/workers/index.js"]
    env_file: .env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  dokploy-network:
    external: true
